# arch-pkgver: 5.0.0
# Ported from pkgbuilds/hyprshade. Completions are generated by invoking the
# installed entry point with click's completion environment variables, the
# same way the Arch package drives them off the built wheel.
EAPI=8

DISTUTILS_USE_PEP517=hatchling
# upstream requires-python >=3.11
PYTHON_COMPAT=( python3_{11..15} )
inherit distutils-r1 shell-completion

DESCRIPTION="Hyprland shade configuration tool"
HOMEPAGE="https://github.com/loqusion/hyprshade"
SRC_URI="
	https://files.pythonhosted.org/packages/source/${PN::1}/${PN}/${P}.tar.gz
	https://raw.githubusercontent.com/loqusion/${PN}/${PV}/examples/config.toml -> ${P}-example-config.toml
"

S="${WORKDIR}/${P}"
LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64 ~arm64"

# Hyprland itself is not packaged in this tree; hyprshade is inert without
# it but installs cleanly (see elog).
RDEPEND="
	dev-python/click[${PYTHON_USEDEP}]
	dev-python/more-itertools[${PYTHON_USEDEP}]
	sys-apps/util-linux
"

python_install_all() {
	distutils-r1_python_install_all

	insinto /usr/share/${PN}/examples
	newins "${DISTDIR}/${P}-example-config.toml" config.toml

	local out="${T}/completions"
	mkdir -p "${out}" || die
	_HYPRSHADE_COMPLETE=bash_source "${D}/usr/bin/${PN}" >"${out}/${PN}.bash" || die
	_HYPRSHADE_COMPLETE=fish_source "${D}/usr/bin/${PN}" >"${out}/${PN}.fish" || die
	_HYPRSHADE_COMPLETE=zsh_source "${D}/usr/bin/${PN}" >"${out}/_${PN}" || die

	newbashcomp "${out}/${PN}.bash" ${PN}
	newfishcomp "${out}/${PN}.fish" ${PN}.fish
	newzshcomp "${out}/_${PN}" _${PN}
}

pkg_postinst() {
	elog "hyprshade drives Hyprland's shade configurator. Hyprland is not"
	elog "packaged in this tree; the tool is only useful once it is available."
	elog "To activate shaders on a schedule, see the systemd timer described"
	elog "in the shipped example under /usr/share/${PN}/examples."
}
