# arch-pkgver: 3.7.3
# Ported from pkgbuilds/dbxcli-bin. Completions are generated by running the
# shipped binary in src_compile, the same way the Arch package drives them.
EAPI=8

inherit shell-completion

DESCRIPTION="A command line client for Dropbox built using the Go SDK"
HOMEPAGE="https://github.com/dropbox/dbxcli"
SRC_URI="
	amd64? ( ${HOMEPAGE}/releases/download/v${PV}/dbxcli_${PV}_linux_amd64.tar.gz -> ${P}-amd64.tar.gz )
	arm64? ( ${HOMEPAGE}/releases/download/v${PV}/dbxcli_${PV}_linux_arm64.tar.gz -> ${P}-arm64.tar.gz )
"

S="${WORKDIR}/dbxcli-${PV}"

LICENSE="Apache-2.0"
SLOT="0"
KEYWORDS="~amd64 ~arm64"

RESTRICT="strip mirror"
QA_PREBUILT="/usr/bin/dbxcli"

src_compile() {
	local sh
	for sh in bash fish zsh; do
		./dbxcli completion "${sh}" > "dbxcli.${sh}" || die "completion ${sh} failed"
	done
}

src_install() {
	dobin dbxcli
	newbashcomp dbxcli.bash dbxcli
	dofishcomp dbxcli.fish
	dozshcomp dbxcli.zsh
	insinto /usr/share/licenses/${PF}
	doins LICENSE
	dodoc README.md
}
